<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-F0SEMFK" failures="1" tests="9" name="PropFTX.Tests.LoginTest" time="49.826" errors="0" timestamp="2023-02-02T10:02:40 IST" skipped="0">
  <testcase classname="PropFTX.Tests.LoginTest" name="withoutEmailPassword" time="4.252"/>
  <system-out/>
  <testcase classname="PropFTX.Tests.LoginTest" name="wrongEmailPassword" time="6.026"/>
  <system-out/>
  <testcase classname="PropFTX.Tests.LoginTest" name="InvalidEmail" time="4.575"/>
  <system-out/>
  <testcase classname="PropFTX.Tests.LoginTest" name="checkPasswordVisibility" time="7.654"/>
  <system-out/>
  <testcase classname="PropFTX.Tests.LoginTest" name="validEmailPassword" time="9.675"/>
  <system-out/>
  <testcase classname="PropFTX.Tests.LoginTest" name="forgotPasswordWithoutEmail" time="3.490"/>
  <system-out/>
  <testcase classname="PropFTX.Tests.LoginTest" name="forgotPasswordInvaliEmail" time="4.555"/>
  <system-out/>
  <testcase classname="PropFTX.Tests.LoginTest" name="forgotPasswordEmailNotExist" time="4.620">
    <failure message="expected [Email not found !] but found [Email not found]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Email not found !] but found [Email not found]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at PropFTX.Tests.LoginTest.forgotPasswordEmailNotExist(LoginTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- forgotPasswordEmailNotExist -->
  <system-out/>
  <testcase classname="PropFTX.Tests.LoginTest" name="forgotPasswordEmailExist" time="4.979"/>
  <system-out/>
</testsuite> <!-- PropFTX.Tests.LoginTest -->
